let MOCK_PRODUCTS = [
  {
    id: 1,
    title: "Wireless Headphones Pro",
    price: 99.99,
    category: "electronics",
    rating: { rate: 4.5, count: 120 },
    image: "/images/headphones.webp",
    description: "High quality wireless headphones with noise cancellation.",
  },
  {
    id: 2,
    title: "Smart Watch Series X",
    price: 149.99,
    category: "electronics",
    rating: { rate: 4.2, count: 89 },
    image: "/images/watch.webp",
    description: "Smart watch with health tracking and GPS.",
  },
  {
    id: 3,
    title: "Running Shoes Ultra",
    price: 79.99,
    category: "clothing",
    rating: { rate: 4.7, count: 200 },
    image: "/images/shoes.webp",
    description: "Lightweight running shoes for professional athletes.",
  },
  {
    id: 4,
    title: "Casual Backpack",
    price: 59.99,
    category: "accessories",
    rating: { rate: 4.3, count: 150 },
    image: "/images/backpack.webp",
    description: "Durable backpack for everyday use.",
  },
  {
    id: 5,
    title: "Men's Slim Fit Shirt",
    price: 39.99,
    category: "clothing",
    rating: { rate: 4.1, count: 95 },
    image: "/images/shirt.webp",
    description: "Classic slim fit shirt for formal occasions.",
  },
  {
    id: 6,
    title: "Women's Jacket",
    price: 89.99,
    category: "clothing",
    rating: { rate: 4.6, count: 180 },
    image: "/images/jacket.webp",
    description: "Warm and stylish jacket for winter.",
  },
  {
    id: 7,
    title: "Gold Bracelet",
    price: 199.99,
    category: "jewelery",
    rating: { rate: 4.8, count: 60 },
    image: "/images/bracelet.webp",
    description: "Elegant gold bracelet for special occasions.",
  },
  {
    id: 8,
    title: "USB-C Hard Drive",
    price: 64.99,
    category: "electronics",
    rating: { rate: 4.4, count: 110 },
    image: "/images/harddrive.webp",
    description: "Portable hard drive with fast USB-C connection.",
  },
  {
    id: 101,
    title: "Bicycle 1",
    price: 199.0,
    category: "bicycles",
    rating: { rate: 4.2, count: 57 },
    image: "/images/products/bicycles-1.webp",
    description: "Bicycle 1 - a great addition to our bicycles collection.",
  },
  {
    id: 102,
    title: "Bicycle 2",
    price: 212.93,
    category: "bicycles",
    rating: { rate: 4.3, count: 64 },
    image: "/images/products/bicycles-2.webp",
    description: "Bicycle 2 - a great addition to our bicycles collection.",
  },
  {
    id: 103,
    title: "Bicycle 3",
    price: 226.86,
    category: "bicycles",
    rating: { rate: 4.5, count: 71 },
    image: "/images/products/bicycles-3.webp",
    description: "Bicycle 3 - a great addition to our bicycles collection.",
  },
  {
    id: 104,
    title: "Bicycle 4",
    price: 240.79,
    category: "bicycles",
    rating: { rate: 4.6, count: 78 },
    image: "/images/products/bicycles-4.webp",
    description: "Bicycle 4 - a great addition to our bicycles collection.",
  },
  {
    id: 105,
    title: "Bicycle 5",
    price: 254.72,
    category: "bicycles",
    rating: { rate: 4.0, count: 85 },
    image: "/images/products/bicycles-5.webp",
    description: "Bicycle 5 - a great addition to our bicycles collection.",
  },
  {
    id: 106,
    title: "Bicycle 6",
    price: 268.65,
    category: "bicycles",
    rating: { rate: 4.2, count: 92 },
    image: "/images/products/bicycles-6.webp",
    description: "Bicycle 6 - a great addition to our bicycles collection.",
  },
  {
    id: 107,
    title: "Bicycle 7",
    price: 282.58,
    category: "bicycles",
    rating: { rate: 4.3, count: 99 },
    image: "/images/products/bicycles-7.webp",
    description: "Bicycle 7 - a great addition to our bicycles collection.",
  },
  {
    id: 108,
    title: "Bicycle 8",
    price: 296.51,
    category: "bicycles",
    rating: { rate: 4.5, count: 106 },
    image: "/images/products/bicycles-8.webp",
    description: "Bicycle 8 - a great addition to our bicycles collection.",
  },
  {
    id: 109,
    title: "Wrist Watch 1",
    price: 89.0,
    category: "watches",
    rating: { rate: 4.2, count: 57 },
    image: "/images/products/watches-9.webp",
    description: "Wrist Watch 1 - a great addition to our watches collection.",
  },
  {
    id: 110,
    title: "Wrist Watch 2",
    price: 95.23,
    category: "watches",
    rating: { rate: 4.3, count: 64 },
    image: "/images/products/watches-10.webp",
    description: "Wrist Watch 2 - a great addition to our watches collection.",
  },
  {
    id: 111,
    title: "Wrist Watch 3",
    price: 101.46,
    category: "watches",
    rating: { rate: 4.5, count: 71 },
    image: "/images/products/watches-11.webp",
    description: "Wrist Watch 3 - a great addition to our watches collection.",
  },
  {
    id: 112,
    title: "Wrist Watch 4",
    price: 107.69,
    category: "watches",
    rating: { rate: 4.6, count: 78 },
    image: "/images/products/watches-12.webp",
    description: "Wrist Watch 4 - a great addition to our watches collection.",
  },
  {
    id: 113,
    title: "Wrist Watch 5",
    price: 113.92,
    category: "watches",
    rating: { rate: 4.0, count: 85 },
    image: "/images/products/watches-13.webp",
    description: "Wrist Watch 5 - a great addition to our watches collection.",
  },
  {
    id: 114,
    title: "Wrist Watch 6",
    price: 120.15,
    category: "watches",
    rating: { rate: 4.2, count: 92 },
    image: "/images/products/watches-14.webp",
    description: "Wrist Watch 6 - a great addition to our watches collection.",
  },
  {
    id: 115,
    title: "Wrist Watch 7",
    price: 126.38,
    category: "watches",
    rating: { rate: 4.3, count: 99 },
    image: "/images/products/watches-15.webp",
    description: "Wrist Watch 7 - a great addition to our watches collection.",
  },
  {
    id: 116,
    title: "Wrist Watch 8",
    price: 132.61,
    category: "watches",
    rating: { rate: 4.5, count: 106 },
    image: "/images/products/watches-16.webp",
    description: "Wrist Watch 8 - a great addition to our watches collection.",
  },
  {
    id: 117,
    title: "Wrist Watch 9",
    price: 138.84,
    category: "watches",
    rating: { rate: 4.6, count: 113 },
    image: "/images/products/watches-17.webp",
    description: "Wrist Watch 9 - a great addition to our watches collection.",
  },
  {
    id: 118,
    title: "Wrist Watch 10",
    price: 145.07,
    category: "watches",
    rating: { rate: 4.0, count: 120 },
    image: "/images/products/watches-18.webp",
    description: "Wrist Watch 10 - a great addition to our watches collection.",
  },
  {
    id: 119,
    title: "Jewelry Piece 1",
    price: 129.0,
    category: "jewelery",
    rating: { rate: 4.2, count: 57 },
    image: "/images/products/jewelery-19.webp",
    description: "Jewelry Piece 1 - a great addition to our jewelery collection.",
  },
  {
    id: 120,
    title: "Jewelry Piece 2",
    price: 138.03,
    category: "jewelery",
    rating: { rate: 4.3, count: 64 },
    image: "/images/products/jewelery-20.webp",
    description: "Jewelry Piece 2 - a great addition to our jewelery collection.",
  },
  {
    id: 121,
    title: "Jewelry Piece 3",
    price: 147.06,
    category: "jewelery",
    rating: { rate: 4.5, count: 71 },
    image: "/images/products/jewelery-21.webp",
    description: "Jewelry Piece 3 - a great addition to our jewelery collection.",
  },
  {
    id: 122,
    title: "Jewelry Piece 4",
    price: 156.09,
    category: "jewelery",
    rating: { rate: 4.6, count: 78 },
    image: "/images/products/jewelery-22.webp",
    description: "Jewelry Piece 4 - a great addition to our jewelery collection.",
  },
  {
    id: 123,
    title: "Jewelry Piece 5",
    price: 165.12,
    category: "jewelery",
    rating: { rate: 4.0, count: 85 },
    image: "/images/products/jewelery-23.webp",
    description: "Jewelry Piece 5 - a great addition to our jewelery collection.",
  },
  {
    id: 124,
    title: "Jewelry Piece 6",
    price: 174.15,
    category: "jewelery",
    rating: { rate: 4.2, count: 92 },
    image: "/images/products/jewelery-24.webp",
    description: "Jewelry Piece 6 - a great addition to our jewelery collection.",
  },
  {
    id: 125,
    title: "Accessory 1",
    price: 25.0,
    category: "accessories",
    rating: { rate: 4.2, count: 57 },
    image: "/images/products/accessories-25.webp",
    description: "Accessory 1 - a great addition to our accessories collection.",
  },
  {
    id: 126,
    title: "Accessory 2",
    price: 26.75,
    category: "accessories",
    rating: { rate: 4.3, count: 64 },
    image: "/images/products/accessories-26.webp",
    description: "Accessory 2 - a great addition to our accessories collection.",
  },
  {
    id: 127,
    title: "Accessory 3",
    price: 28.5,
    category: "accessories",
    rating: { rate: 4.5, count: 71 },
    image: "/images/products/accessories-27.webp",
    description: "Accessory 3 - a great addition to our accessories collection.",
  },
  {
    id: 128,
    title: "Accessory 4",
    price: 30.25,
    category: "accessories",
    rating: { rate: 4.6, count: 78 },
    image: "/images/products/accessories-28.webp",
    description: "Accessory 4 - a great addition to our accessories collection.",
  },
  {
    id: 129,
    title: "Accessory 5",
    price: 32.0,
    category: "accessories",
    rating: { rate: 4.0, count: 85 },
    image: "/images/products/accessories-29.webp",
    description: "Accessory 5 - a great addition to our accessories collection.",
  },
  {
    id: 130,
    title: "Swimming Gear 1",
    price: 35.0,
    category: "swimming",
    rating: { rate: 4.2, count: 57 },
    image: "/images/products/swimming-30.webp",
    description: "Swimming Gear 1 - a great addition to our swimming collection.",
  },
  {
    id: 131,
    title: "Swimming Gear 2",
    price: 37.45,
    category: "swimming",
    rating: { rate: 4.3, count: 64 },
    image: "/images/products/swimming-31.webp",
    description: "Swimming Gear 2 - a great addition to our swimming collection.",
  },
  {
    id: 132,
    title: "Swimming Gear 3",
    price: 39.9,
    category: "swimming",
    rating: { rate: 4.5, count: 71 },
    image: "/images/products/swimming-32.webp",
    description: "Swimming Gear 3 - a great addition to our swimming collection.",
  },
  {
    id: 133,
    title: "Swimming Gear 4",
    price: 42.35,
    category: "swimming",
    rating: { rate: 4.6, count: 78 },
    image: "/images/products/swimming-33.webp",
    description: "Swimming Gear 4 - a great addition to our swimming collection.",
  },
  {
    id: 134,
    title: "Swimming Gear 5",
    price: 44.8,
    category: "swimming",
    rating: { rate: 4.0, count: 85 },
    image: "/images/products/swimming-34.webp",
    description: "Swimming Gear 5 - a great addition to our swimming collection.",
  },
  {
    id: 135,
    title: "Men's Clothing Item 1",
    price: 45.0,
    category: "clothing",
    rating: { rate: 4.2, count: 57 },
    image: "/images/products/clothing-35.webp",
    description: "Men's Clothing Item 1 - a great addition to our clothing collection.",
  },
  {
    id: 136,
    title: "Men's Clothing Item 2",
    price: 48.15,
    category: "clothing",
    rating: { rate: 4.3, count: 64 },
    image: "/images/products/clothing-36.webp",
    description: "Men's Clothing Item 2 - a great addition to our clothing collection.",
  },
  {
    id: 137,
    title: "Men's Clothing Item 3",
    price: 51.3,
    category: "clothing",
    rating: { rate: 4.5, count: 71 },
    image: "/images/products/clothing-37.webp",
    description: "Men's Clothing Item 3 - a great addition to our clothing collection.",
  },
  {
    id: 138,
    title: "Men's Clothing Item 4",
    price: 54.45,
    category: "clothing",
    rating: { rate: 4.6, count: 78 },
    image: "/images/products/clothing-38.webp",
    description: "Men's Clothing Item 4 - a great addition to our clothing collection.",
  },
  {
    id: 139,
    title: "Women's Clothing Item 1",
    price: 49.0,
    category: "clothing",
    rating: { rate: 4.2, count: 57 },
    image: "/images/products/clothing-39.webp",
    description: "Women's Clothing Item 1 - a great addition to our clothing collection.",
  },
  {
    id: 140,
    title: "Women's Clothing Item 2",
    price: 52.43,
    category: "clothing",
    rating: { rate: 4.3, count: 64 },
    image: "/images/products/clothing-40.webp",
    description: "Women's Clothing Item 2 - a great addition to our clothing collection.",
  },
  {
    id: 141,
    title: "Women's Clothing Item 3",
    price: 55.86,
    category: "clothing",
    rating: { rate: 4.5, count: 71 },
    image: "/images/products/clothing-41.webp",
    description: "Women's Clothing Item 3 - a great addition to our clothing collection.",
  },
  {
    id: 142,
    title: "Women's Clothing Item 4",
    price: 59.29,
    category: "clothing",
    rating: { rate: 4.6, count: 78 },
    image: "/images/products/clothing-42.webp",
    description: "Women's Clothing Item 4 - a great addition to our clothing collection.",
  },
  {
    id: 143,
    title: "Women's Clothing Item 5",
    price: 62.72,
    category: "clothing",
    rating: { rate: 4.0, count: 85 },
    image: "/images/products/clothing-43.webp",
    description: "Women's Clothing Item 5 - a great addition to our clothing collection.",
  },
  {
    id: 144,
    title: "Toy Car 1",
    price: 19.0,
    category: "toys",
    rating: { rate: 4.2, count: 57 },
    image: "/images/products/toys-44.webp",
    description: "Toy Car 1 - a great addition to our toys collection.",
  },
  {
    id: 145,
    title: "Toy Car 2",
    price: 20.33,
    category: "toys",
    rating: { rate: 4.3, count: 64 },
    image: "/images/products/toys-45.webp",
    description: "Toy Car 2 - a great addition to our toys collection.",
  },
  {
    id: 146,
    title: "Toy Car 3",
    price: 21.66,
    category: "toys",
    rating: { rate: 4.5, count: 71 },
    image: "/images/products/toys-46.webp",
    description: "Toy Car 3 - a great addition to our toys collection.",
  },
  {
    id: 147,
    title: "Toy Car 4",
    price: 22.99,
    category: "toys",
    rating: { rate: 4.6, count: 78 },
    image: "/images/products/toys-47.webp",
    description: "Toy Car 4 - a great addition to our toys collection.",
  },
  {
    id: 148,
    title: "Toy 1",
    price: 15.0,
    category: "toys",
    rating: { rate: 4.2, count: 57 },
    image: "/images/products/toys-48.webp",
    description: "Toy 1 - a great addition to our toys collection.",
  },
  {
    id: 149,
    title: "Toy 2",
    price: 16.05,
    category: "toys",
    rating: { rate: 4.3, count: 64 },
    image: "/images/products/toys-49.webp",
    description: "Toy 2 - a great addition to our toys collection.",
  },
  {
    id: 150,
    title: "Toy 3",
    price: 17.1,
    category: "toys",
    rating: { rate: 4.5, count: 71 },
    image: "/images/products/toys-50.webp",
    description: "Toy 3 - a great addition to our toys collection.",
  },
  {
    id: 151,
    title: "Toy 4",
    price: 18.15,
    category: "toys",
    rating: { rate: 4.6, count: 78 },
    image: "/images/products/toys-51.webp",
    description: "Toy 4 - a great addition to our toys collection.",
  },
  {
    id: 152,
    title: "Toy 5",
    price: 19.2,
    category: "toys",
    rating: { rate: 4.0, count: 85 },
    image: "/images/products/toys-52.webp",
    description: "Toy 5 - a great addition to our toys collection.",
  },
  {
    id: 153,
    title: "Toy 6",
    price: 20.25,
    category: "toys",
    rating: { rate: 4.2, count: 92 },
    image: "/images/products/toys-53.webp",
    description: "Toy 6 - a great addition to our toys collection.",
  },
  {
    id: 154,
    title: "Toy Plane 1",
    price: 22.0,
    category: "toys",
    rating: { rate: 4.2, count: 57 },
    image: "/images/products/toys-54.webp",
    description: "Toy Plane 1 - a great addition to our toys collection.",
  },
  {
    id: 155,
    title: "Toy Plane 2",
    price: 23.54,
    category: "toys",
    rating: { rate: 4.3, count: 64 },
    image: "/images/products/toys-55.webp",
    description: "Toy Plane 2 - a great addition to our toys collection.",
  },
  {
    id: 156,
    title: "Toy Plane 3",
    price: 25.08,
    category: "toys",
    rating: { rate: 4.5, count: 71 },
    image: "/images/products/toys-56.webp",
    description: "Toy Plane 3 - a great addition to our toys collection.",
  },
  {
    id: 157,
    title: "Toy Plane 4",
    price: 26.62,
    category: "toys",
    rating: { rate: 4.6, count: 78 },
    image: "/images/products/toys-57.webp",
    description: "Toy Plane 4 - a great addition to our toys collection.",
  },
  {
    id: 158,
    title: "Toy Plane 5",
    price: 28.16,
    category: "toys",
    rating: { rate: 4.0, count: 85 },
    image: "/images/products/toys-58.webp",
    description: "Toy Plane 5 - a great addition to our toys collection.",
  },
  {
    id: 159,
    title: "Toy Plane 6",
    price: 29.7,
    category: "toys",
    rating: { rate: 4.2, count: 92 },
    image: "/images/products/toys-59.webp",
    description: "Toy Plane 6 - a great addition to our toys collection.",
  },
  {
    id: 160,
    title: "Toy Plane 7",
    price: 31.24,
    category: "toys",
    rating: { rate: 4.3, count: 99 },
    image: "/images/products/toys-60.webp",
    description: "Toy Plane 7 - a great addition to our toys collection.",
  },
  {
    id: 161,
    title: "Laptop 1",
    price: 699.0,
    category: "electronics",
    rating: { rate: 4.2, count: 57 },
    image: "/images/products/electronics-61.webp",
    description: "Laptop 1 - a great addition to our electronics collection.",
  },
  {
    id: 162,
    title: "Laptop 2",
    price: 747.93,
    category: "electronics",
    rating: { rate: 4.3, count: 64 },
    image: "/images/products/electronics-62.webp",
    description: "Laptop 2 - a great addition to our electronics collection.",
  },
  {
    id: 163,
    title: "Laptop 3",
    price: 796.86,
    category: "electronics",
    rating: { rate: 4.5, count: 71 },
    image: "/images/products/electronics-63.webp",
    description: "Laptop 3 - a great addition to our electronics collection.",
  },
  {
    id: 164,
    title: "Laptop 4",
    price: 845.79,
    category: "electronics",
    rating: { rate: 4.6, count: 78 },
    image: "/images/products/electronics-64.webp",
    description: "Laptop 4 - a great addition to our electronics collection.",
  },
  {
    id: 165,
    title: "Laptop 5",
    price: 894.72,
    category: "electronics",
    rating: { rate: 4.0, count: 85 },
    image: "/images/products/electronics-65.webp",
    description: "Laptop 5 - a great addition to our electronics collection.",
  },
  {
    id: 166,
    title: "Laptop 6",
    price: 943.65,
    category: "electronics",
    rating: { rate: 4.2, count: 92 },
    image: "/images/products/electronics-66.webp",
    description: "Laptop 6 - a great addition to our electronics collection.",
  },
  {
    id: 167,
    title: "Laptop 7",
    price: 992.58,
    category: "electronics",
    rating: { rate: 4.3, count: 99 },
    image: "/images/products/electronics-67.webp",
    description: "Laptop 7 - a great addition to our electronics collection.",
  },
  {
    id: 168,
    title: "Laptop 8",
    price: 1041.51,
    category: "electronics",
    rating: { rate: 4.5, count: 106 },
    image: "/images/products/electronics-68.webp",
    description: "Laptop 8 - a great addition to our electronics collection.",
  },
  {
    id: 169,
    title: "Laptop 9",
    price: 1090.44,
    category: "electronics",
    rating: { rate: 4.6, count: 113 },
    image: "/images/products/electronics-69.webp",
    description: "Laptop 9 - a great addition to our electronics collection.",
  },
  {
    id: 170,
    title: "Laptop 10",
    price: 1139.37,
    category: "electronics",
    rating: { rate: 4.0, count: 120 },
    image: "/images/products/electronics-70.webp",
    description: "Laptop 10 - a great addition to our electronics collection.",
  },
  {
    id: 171,
    title: "Laptop 11",
    price: 1188.3,
    category: "electronics",
    rating: { rate: 4.2, count: 127 },
    image: "/images/products/electronics-71.webp",
    description: "Laptop 11 - a great addition to our electronics collection.",
  },
  {
    id: 172,
    title: "Video Game 1",
    price: 59.0,
    category: "electronics",
    rating: { rate: 4.2, count: 57 },
    image: "/images/products/electronics-72.webp",
    description: "Video Game 1 - a great addition to our electronics collection.",
  },
  {
    id: 173,
    title: "Video Game 2",
    price: 63.13,
    category: "electronics",
    rating: { rate: 4.3, count: 64 },
    image: "/images/products/electronics-73.webp",
    description: "Video Game 2 - a great addition to our electronics collection.",
  },
  {
    id: 174,
    title: "Video Game 3",
    price: 67.26,
    category: "electronics",
    rating: { rate: 4.5, count: 71 },
    image: "/images/products/electronics-74.webp",
    description: "Video Game 3 - a great addition to our electronics collection.",
  },
  {
    id: 175,
    title: "Video Game 4",
    price: 71.39,
    category: "electronics",
    rating: { rate: 4.6, count: 78 },
    image: "/images/products/electronics-75.webp",
    description: "Video Game 4 - a great addition to our electronics collection.",
  },
  {
    id: 176,
    title: "Video Game 5",
    price: 75.52,
    category: "electronics",
    rating: { rate: 4.0, count: 85 },
    image: "/images/products/electronics-76.webp",
    description: "Video Game 5 - a great addition to our electronics collection.",
  },
  {
    id: 177,
    title: "Video Game 6",
    price: 79.65,
    category: "electronics",
    rating: { rate: 4.2, count: 92 },
    image: "/images/products/electronics-77.webp",
    description: "Video Game 6 - a great addition to our electronics collection.",
  },
  {
    id: 178,
    title: "Video Game 7",
    price: 83.78,
    category: "electronics",
    rating: { rate: 4.3, count: 99 },
    image: "/images/products/electronics-78.webp",
    description: "Video Game 7 - a great addition to our electronics collection.",
  },
  {
    id: 179,
    title: "Video Game 8",
    price: 87.91,
    category: "electronics",
    rating: { rate: 4.5, count: 106 },
    image: "/images/products/electronics-79.webp",
    description: "Video Game 8 - a great addition to our electronics collection.",
  },
  {
    id: 180,
    title: "TV Screen 1",
    price: 459.0,
    category: "electronics",
    rating: { rate: 4.2, count: 57 },
    image: "/images/products/electronics-80.webp",
    description: "TV Screen 1 - a great addition to our electronics collection.",
  },
  {
    id: 181,
    title: "TV Screen 2",
    price: 491.13,
    category: "electronics",
    rating: { rate: 4.3, count: 64 },
    image: "/images/products/electronics-81.webp",
    description: "TV Screen 2 - a great addition to our electronics collection.",
  },
  {
    id: 182,
    title: "TV Screen 3",
    price: 523.26,
    category: "electronics",
    rating: { rate: 4.5, count: 71 },
    image: "/images/products/electronics-82.webp",
    description: "TV Screen 3 - a great addition to our electronics collection.",
  },
  {
    id: 183,
    title: "TV Screen 4",
    price: 555.39,
    category: "electronics",
    rating: { rate: 4.6, count: 78 },
    image: "/images/products/electronics-83.webp",
    description: "TV Screen 4 - a great addition to our electronics collection.",
  },
  {
    id: 184,
    title: "TV Screen 5",
    price: 587.52,
    category: "electronics",
    rating: { rate: 4.0, count: 85 },
    image: "/images/products/electronics-84.webp",
    description: "TV Screen 5 - a great addition to our electronics collection.",
  },
  {
    id: 185,
    title: "TV Screen 6",
    price: 619.65,
    category: "electronics",
    rating: { rate: 4.2, count: 92 },
    image: "/images/products/electronics-85.webp",
    description: "TV Screen 6 - a great addition to our electronics collection.",
  },
  {
    id: 186,
    title: "TV Screen 7",
    price: 651.78,
    category: "electronics",
    rating: { rate: 4.3, count: 99 },
    image: "/images/products/electronics-86.webp",
    description: "TV Screen 7 - a great addition to our electronics collection.",
  },
  {
    id: 187,
    title: "TV Screen 8",
    price: 683.91,
    category: "electronics",
    rating: { rate: 4.5, count: 106 },
    image: "/images/products/electronics-87.webp",
    description: "TV Screen 8 - a great addition to our electronics collection.",
  },
  {
    id: 188,
    title: "Tablet 1",
    price: 299.0,
    category: "electronics",
    rating: { rate: 4.2, count: 57 },
    image: "/images/products/electronics-88.webp",
    description: "Tablet 1 - a great addition to our electronics collection.",
  },
  {
    id: 189,
    title: "Tablet 2",
    price: 319.93,
    category: "electronics",
    rating: { rate: 4.3, count: 64 },
    image: "/images/products/electronics-89.webp",
    description: "Tablet 2 - a great addition to our electronics collection.",
  },
  {
    id: 190,
    title: "Tablet 3",
    price: 340.86,
    category: "electronics",
    rating: { rate: 4.5, count: 71 },
    image: "/images/products/electronics-90.webp",
    description: "Tablet 3 - a great addition to our electronics collection.",
  },
  {
    id: 191,
    title: "Tablet 4",
    price: 361.79,
    category: "electronics",
    rating: { rate: 4.6, count: 78 },
    image: "/images/products/electronics-91.webp",
    description: "Tablet 4 - a great addition to our electronics collection.",
  },
  {
    id: 192,
    title: "Tablet 5",
    price: 382.72,
    category: "electronics",
    rating: { rate: 4.0, count: 85 },
    image: "/images/products/electronics-92.webp",
    description: "Tablet 5 - a great addition to our electronics collection.",
  },
  {
    id: 193,
    title: "Tablet 6",
    price: 403.65,
    category: "electronics",
    rating: { rate: 4.2, count: 92 },
    image: "/images/products/electronics-93.webp",
    description: "Tablet 6 - a great addition to our electronics collection.",
  },
  {
    id: 194,
    title: "Headphones 1",
    price: 79.0,
    category: "electronics",
    rating: { rate: 4.2, count: 57 },
    image: "/images/products/electronics-94.webp",
    description: "Headphones 1 - a great addition to our electronics collection.",
  },
  {
    id: 195,
    title: "Headphones 2",
    price: 84.53,
    category: "electronics",
    rating: { rate: 4.3, count: 64 },
    image: "/images/products/electronics-95.webp",
    description: "Headphones 2 - a great addition to our electronics collection.",
  },
  {
    id: 196,
    title: "Headphones 3",
    price: 90.06,
    category: "electronics",
    rating: { rate: 4.5, count: 71 },
    image: "/images/products/electronics-96.webp",
    description: "Headphones 3 - a great addition to our electronics collection.",
  },
  {
    id: 197,
    title: "Headphones 4",
    price: 95.59,
    category: "electronics",
    rating: { rate: 4.6, count: 78 },
    image: "/images/products/electronics-97.webp",
    description: "Headphones 4 - a great addition to our electronics collection.",
  },
  {
    id: 198,
    title: "Headphones 5",
    price: 101.12,
    category: "electronics",
    rating: { rate: 4.0, count: 85 },
    image: "/images/products/electronics-98.webp",
    description: "Headphones 5 - a great addition to our electronics collection.",
  },
  {
    id: 199,
    title: "Headphones 6",
    price: 106.65,
    category: "electronics",
    rating: { rate: 4.2, count: 92 },
    image: "/images/products/electronics-99.webp",
    description: "Headphones 6 - a great addition to our electronics collection.",
  },
  {
    id: 200,
    title: "Headphones 7",
    price: 112.18,
    category: "electronics",
    rating: { rate: 4.3, count: 99 },
    image: "/images/products/electronics-100.webp",
    description: "Headphones 7 - a great addition to our electronics collection.",
  },
  {
    id: 201,
    title: "Headphones 8",
    price: 117.71,
    category: "electronics",
    rating: { rate: 4.5, count: 106 },
    image: "/images/products/electronics-101.webp",
    description: "Headphones 8 - a great addition to our electronics collection.",
  },
  {
    id: 202,
    title: "Headphones 9",
    price: 123.24,
    category: "electronics",
    rating: { rate: 4.6, count: 113 },
    image: "/images/products/electronics-102.webp",
    description: "Headphones 9 - a great addition to our electronics collection.",
  },
  {
    id: 203,
    title: "Headphones 10",
    price: 128.77,
    category: "electronics",
    rating: { rate: 4.0, count: 120 },
    image: "/images/products/electronics-103.webp",
    description: "Headphones 10 - a great addition to our electronics collection.",
  },
  {
    id: 204,
    title: "Samsung Phone 1",
    price: 799.0,
    category: "electronics",
    rating: { rate: 4.2, count: 57 },
    image: "/images/products/electronics-104.webp",
    description: "Samsung Phone 1 - a great addition to our electronics collection.",
  },
  {
    id: 205,
    title: "Samsung Phone 2",
    price: 854.93,
    category: "electronics",
    rating: { rate: 4.3, count: 64 },
    image: "/images/products/electronics-105.webp",
    description: "Samsung Phone 2 - a great addition to our electronics collection.",
  },
  {
    id: 206,
    title: "Samsung Phone 3",
    price: 910.86,
    category: "electronics",
    rating: { rate: 4.5, count: 71 },
    image: "/images/products/electronics-106.webp",
    description: "Samsung Phone 3 - a great addition to our electronics collection.",
  },
  {
    id: 207,
    title: "Samsung Phone 4",
    price: 966.79,
    category: "electronics",
    rating: { rate: 4.6, count: 78 },
    image: "/images/products/electronics-107.webp",
    description: "Samsung Phone 4 - a great addition to our electronics collection.",
  },
  {
    id: 208,
    title: "Samsung Phone 5",
    price: 1022.72,
    category: "electronics",
    rating: { rate: 4.0, count: 85 },
    image: "/images/products/electronics-108.webp",
    description: "Samsung Phone 5 - a great addition to our electronics collection.",
  },
  {
    id: 209,
    title: "Samsung Phone 6",
    price: 1078.65,
    category: "electronics",
    rating: { rate: 4.2, count: 92 },
    image: "/images/products/electronics-109.webp",
    description: "Samsung Phone 6 - a great addition to our electronics collection.",
  },
  {
    id: 210,
    title: "Samsung Phone 7",
    price: 1134.58,
    category: "electronics",
    rating: { rate: 4.3, count: 99 },
    image: "/images/products/electronics-110.webp",
    description: "Samsung Phone 7 - a great addition to our electronics collection.",
  },
  {
    id: 211,
    title: "Oppo Phone 1",
    price: 399.0,
    category: "electronics",
    rating: { rate: 4.2, count: 57 },
    image: "/images/products/electronics-111.webp",
    description: "Oppo Phone 1 - a great addition to our electronics collection.",
  },
  {
    id: 212,
    title: "Oppo Phone 2",
    price: 426.93,
    category: "electronics",
    rating: { rate: 4.3, count: 64 },
    image: "/images/products/electronics-112.webp",
    description: "Oppo Phone 2 - a great addition to our electronics collection.",
  },
  {
    id: 213,
    title: "Oppo Phone 3",
    price: 454.86,
    category: "electronics",
    rating: { rate: 4.5, count: 71 },
    image: "/images/products/electronics-113.webp",
    description: "Oppo Phone 3 - a great addition to our electronics collection.",
  },
  {
    id: 214,
    title: "Oppo Phone 4",
    price: 482.79,
    category: "electronics",
    rating: { rate: 4.6, count: 78 },
    image: "/images/products/electronics-114.webp",
    description: "Oppo Phone 4 - a great addition to our electronics collection.",
  },
  {
    id: 215,
    title: "Oppo Phone 5",
    price: 510.72,
    category: "electronics",
    rating: { rate: 4.0, count: 85 },
    image: "/images/products/electronics-115.webp",
    description: "Oppo Phone 5 - a great addition to our electronics collection.",
  },
  {
    id: 216,
    title: "Oppo Phone 6",
    price: 538.65,
    category: "electronics",
    rating: { rate: 4.2, count: 92 },
    image: "/images/products/electronics-116.webp",
    description: "Oppo Phone 6 - a great addition to our electronics collection.",
  },
  {
    id: 217,
    title: "Oppo Phone 7",
    price: 566.58,
    category: "electronics",
    rating: { rate: 4.3, count: 99 },
    image: "/images/products/electronics-117.webp",
    description: "Oppo Phone 7 - a great addition to our electronics collection.",
  },
  {
    id: 218,
    title: "Infinix Phone 1",
    price: 249.0,
    category: "electronics",
    rating: { rate: 4.2, count: 57 },
    image: "/images/products/electronics-118.webp",
    description: "Infinix Phone 1 - a great addition to our electronics collection.",
  },
  {
    id: 219,
    title: "Infinix Phone 2",
    price: 266.43,
    category: "electronics",
    rating: { rate: 4.3, count: 64 },
    image: "/images/products/electronics-119.webp",
    description: "Infinix Phone 2 - a great addition to our electronics collection.",
  },
  {
    id: 220,
    title: "Infinix Phone 3",
    price: 283.86,
    category: "electronics",
    rating: { rate: 4.5, count: 71 },
    image: "/images/products/electronics-120.webp",
    description: "Infinix Phone 3 - a great addition to our electronics collection.",
  },
  {
    id: 221,
    title: "Infinix Phone 4",
    price: 301.29,
    category: "electronics",
    rating: { rate: 4.6, count: 78 },
    image: "/images/products/electronics-121.webp",
    description: "Infinix Phone 4 - a great addition to our electronics collection.",
  },
  {
    id: 222,
    title: "Infinix Phone 5",
    price: 318.72,
    category: "electronics",
    rating: { rate: 4.0, count: 85 },
    image: "/images/products/electronics-122.webp",
    description: "Infinix Phone 5 - a great addition to our electronics collection.",
  },
  {
    id: 223,
    title: "Infinix Phone 6",
    price: 336.15,
    category: "electronics",
    rating: { rate: 4.2, count: 92 },
    image: "/images/products/electronics-123.webp",
    description: "Infinix Phone 6 - a great addition to our electronics collection.",
  },
  {
    id: 224,
    title: "Infinix Phone 7",
    price: 353.58,
    category: "electronics",
    rating: { rate: 4.3, count: 99 },
    image: "/images/products/electronics-124.webp",
    description: "Infinix Phone 7 - a great addition to our electronics collection.",
  },
  {
    id: 225,
    title: "Infinix Phone 8",
    price: 371.01,
    category: "electronics",
    rating: { rate: 4.5, count: 106 },
    image: "/images/products/electronics-125.webp",
    description: "Infinix Phone 8 - a great addition to our electronics collection.",
  },
  {
    id: 226,
    title: "Infinix Phone 9",
    price: 388.44,
    category: "electronics",
    rating: { rate: 4.6, count: 113 },
    image: "/images/products/electronics-126.webp",
    description: "Infinix Phone 9 - a great addition to our electronics collection.",
  },
  {
    id: 227,
    title: "iPhone 1",
    price: 1099.0,
    category: "electronics",
    rating: { rate: 4.2, count: 57 },
    image: "/images/products/electronics-127.webp",
    description: "iPhone 1 - a great addition to our electronics collection.",
  },
  {
    id: 228,
    title: "iPhone 2",
    price: 1175.93,
    category: "electronics",
    rating: { rate: 4.3, count: 64 },
    image: "/images/products/electronics-128.webp",
    description: "iPhone 2 - a great addition to our electronics collection.",
  },
  {
    id: 229,
    title: "iPhone 3",
    price: 1252.86,
    category: "electronics",
    rating: { rate: 4.5, count: 71 },
    image: "/images/products/electronics-129.webp",
    description: "iPhone 3 - a great addition to our electronics collection.",
  },
  {
    id: 230,
    title: "iPhone 4",
    price: 1329.79,
    category: "electronics",
    rating: { rate: 4.6, count: 78 },
    image: "/images/products/electronics-130.webp",
    description: "iPhone 4 - a great addition to our electronics collection.",
  },
  {
    id: 231,
    title: "iPhone 5",
    price: 1406.72,
    category: "electronics",
    rating: { rate: 4.0, count: 85 },
    image: "/images/products/electronics-131.webp",
    description: "iPhone 5 - a great addition to our electronics collection.",
  },
  {
    id: 232,
    title: "Smartphone 1",
    price: 349.0,
    category: "electronics",
    rating: { rate: 4.2, count: 57 },
    image: "/images/products/electronics-132.webp",
    description: "Smartphone 1 - a great addition to our electronics collection.",
  },
  {
    id: 233,
    title: "Smartphone 2",
    price: 373.43,
    category: "electronics",
    rating: { rate: 4.3, count: 64 },
    image: "/images/products/electronics-133.webp",
    description: "Smartphone 2 - a great addition to our electronics collection.",
  },
  {
    id: 234,
    title: "Smartphone 3",
    price: 397.86,
    category: "electronics",
    rating: { rate: 4.5, count: 71 },
    image: "/images/products/electronics-134.webp",
    description: "Smartphone 3 - a great addition to our electronics collection.",
  },
  {
    id: 235,
    title: "Smartphone 4",
    price: 422.29,
    category: "electronics",
    rating: { rate: 4.6, count: 78 },
    image: "/images/products/electronics-135.webp",
    description: "Smartphone 4 - a great addition to our electronics collection.",
  },
  {
    id: 236,
    title: "Smartphone 5",
    price: 446.72,
    category: "electronics",
    rating: { rate: 4.0, count: 85 },
    image: "/images/products/electronics-136.webp",
    description: "Smartphone 5 - a great addition to our electronics collection.",
  },
  {
    id: 237,
    title: "Smartphone 6",
    price: 471.15,
    category: "electronics",
    rating: { rate: 4.2, count: 92 },
    image: "/images/products/electronics-137.webp",
    description: "Smartphone 6 - a great addition to our electronics collection.",
  },
  {
    id: 238,
    title: "Smartphone 7",
    price: 495.58,
    category: "electronics",
    rating: { rate: 4.3, count: 99 },
    image: "/images/products/electronics-138.webp",
    description: "Smartphone 7 - a great addition to our electronics collection.",
  },
  {
    id: 239,
    title: "Smartphone 8",
    price: 520.01,
    category: "electronics",
    rating: { rate: 4.5, count: 106 },
    image: "/images/products/electronics-139.webp",
    description: "Smartphone 8 - a great addition to our electronics collection.",
  },
  {
    id: 240,
    title: "Smartphone 9",
    price: 544.44,
    category: "electronics",
    rating: { rate: 4.6, count: 113 },
    image: "/images/products/electronics-140.webp",
    description: "Smartphone 9 - a great addition to our electronics collection.",
  },
  {
    id: 241,
    title: "Smartphone 10",
    price: 568.87,
    category: "electronics",
    rating: { rate: 4.0, count: 120 },
    image: "/images/products/electronics-141.webp",
    description: "Smartphone 10 - a great addition to our electronics collection.",
  },
  {
    id: 242,
    title: "Smartphone 11",
    price: 593.3,
    category: "electronics",
    rating: { rate: 4.2, count: 127 },
    image: "/images/products/electronics-142.webp",
    description: "Smartphone 11 - a great addition to our electronics collection.",
  },
  {
    id: 243,
    title: "Smartphone 12",
    price: 617.73,
    category: "electronics",
    rating: { rate: 4.3, count: 134 },
    image: "/images/products/electronics-143.webp",
    description: "Smartphone 12 - a great addition to our electronics collection.",
  },
  {
    id: 244,
    title: "Smartphone 13",
    price: 642.16,
    category: "electronics",
    rating: { rate: 4.5, count: 141 },
    image: "/images/products/electronics-144.webp",
    description: "Smartphone 13 - a great addition to our electronics collection.",
  },
];

export const getAllProducts = async () => [...MOCK_PRODUCTS];

export const getProductById = async (id) =>
  MOCK_PRODUCTS.find((p) => p.id === Number(id)) || null;

export const getCategories = async () =>
  [...new Set(MOCK_PRODUCTS.map((p) => p.category))];

export const getProductsByCategory = async (category) =>
  MOCK_PRODUCTS.filter((p) => p.category === category);

export const addProduct = (product) => {
  const newProduct = {
    ...product,
    id: Date.now(),
    rating: { rate: Number(product.rating) || 0, count: 0 },
  };
  MOCK_PRODUCTS = [...MOCK_PRODUCTS, newProduct];
  return newProduct;
};

export const updateProduct = (id, updatedData) => {
  MOCK_PRODUCTS = MOCK_PRODUCTS.map((p) =>
    p.id === Number(id)
      ? {
          ...p,
          ...updatedData,
          rating: { rate: Number(updatedData.rating) || p.rating.rate, count: p.rating.count },
        }
      : p
  );
};

export const deleteProduct = (id) => {
  MOCK_PRODUCTS = MOCK_PRODUCTS.filter((p) => p.id !== Number(id));
};